### ISSUE TITLE
Flatpak | Missing developer/project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [audacity/audacity#2745]
**Description**
Hello. The worth mentioning developer/project/organisation name is missing from present project's metadata file – usually XML. As a result it is
- not exhibited at https://flathub.org/apps/. 
- reported as "Unknown" by Flatseal

**To Reproduce**
1. Install Flatpak applications github.tchx84.Flatseal and org.audacityteam.Audacity
2. Start Flatseal | '`flatpak run com.github.tchx84.Flatseal`'
3. Select _Audacity_
4. Inspect headers.

**Expected behavior**
Presence of developer/project/organisation **name**

**Screenshot**

![Flatpak_Flatseal_Audacity](https://user-images.githubusercontent.com/26058215/160832742-1bb095cf-bbc8-4413-95a9-733fa4ab18ca.png)

Action required for fixing lasts at most two minutes so the ticket could be closed yet today. Involved value is part of the application [metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name). That requires the addition of  `<developer_name>Muse Group</developer_name>` into that model of XML
```xml
<?xml version="1.0" encoding="utf-8"?>
<component type="desktop">
 ...
</component>
```

**Comment by crsib** [comment]
I think this issue should go to https://github.com/flathub/org.audacityteam.Audacity

We do not maintain the Flatpack builds.

**Comment by Ricky-Tigg** [comment]
The involved [file](https://github.com/audacity/audacity/blob/Audacity-3.1.3/help/audacity.appdata.xml) did exist here!

**Comment by LWinterberg** [comment]
oh dear, so *that's* why it still is showing up with the "what's new in this ancient version"!

@Ricky-Tigg do you want to update the file yourself in the current master?

**Comment by Ricky-Tigg** [comment]
As for any project, relying on third party to implement a patch fully instructed is without exception unwise. The fix could have already been brought by the time "_I think this issue should go to_" was written.

**Comment by sahilsekr42** [comment]
I have reproduced this issue on my linux system .The steps I believe should solve this(please correct me if I am wrong) are:--

1.Edit the local copy of audacity/audacity.appdata.xml by adding  <developer_name>Muse Group</developer_name> tag under      the  component tag section
2.commit this and push to my forked repository and generate a PR and sign cla.

Please assign this to me if I am correct,

**Comment by Ricky-Tigg** [comment]
Don't hesitate to have trust in yourself. Your first step is a correct interpretation of the instructions.

**Comment by sahilsekr42** [comment]
Thanks @Ricky-Tigg . I have created a PR for review btw..

**Comment by Ricky-Tigg** [comment]
@LWinterberg | `flatpak -y update` | Unless the update of the Flathub repository is pending, the issue is still alive as you can notice  it by yourself.

**Comment by LWinterberg** [comment]
Flathub has the current release version, 3.1.3. It will update with the next release.
