### ISSUE TITLE
display does not update correctly when GTK_IM_MODULE=xim in the environment

### ISSUE THREAD

**Issue by dkg** [audacity/audacity#454]
I'm using Audacity 2.3.3-1 on Debian testing/unstable, on an x86_64 platform, under an X11 session.  The graphics hardware is an intel chipset, using Linux kernel module `i915.ko` (on a [ThinkPad X220](https://www.thinkwiki.org/wiki/Category:X220)).

If i launch audacity as:

```
export GTK_IM_MODULE=xim
audacity
```

then the graphical display doesn't update correctly.

Here is a screenshot:
![audacity-renderfail](https://user-images.githubusercontent.com/66738/76591461-cdf66280-64c6-11ea-89a8-f2cc68266433.png)

And here is a zipped up screencast of the rendering failing (i don't know how to get github to display it in the webpage, sorry):
[audacity.mp4.zip](https://github.com/audacity/audacity/files/4327952/audacity.mp4.zip)

It turns out that if i unset the `GTK_IM_MODULE` environment variable, this problem doesn't happen.  The following command works fine:

```
GTK_IM_MODULE= audacity
``` 

(This was originally reported via the debian BTS at https://bugs.debian.org/935173, and the diagnosis about `GTK_IM_MODULE=xim` was made by Yuri D'Elia)

[gtk dev notes about `GTK_IM_MODULE`](https://developer.gnome.org/gtk3/stable/gtk-running.html)

I have no idea why the choice of an input method would affect screen rendering.

**Comment by Bill-Gray** [comment]
For me,  the original title was closer to truth.   (Audacity 2.3.3 on Xubuntu 20.04.)  For example,  the opening 'how to get help' dialog would appear and I'd click OK,  and the display would not update : the dialog would remain on-screen.  Select a menu and click on an option,  and it would work,  but the menu would remain on-screen.
Resize the window,  and everything gets updated then.  So I had to resize rather frequently to see (for example) the sound I was recording.
Resetting GTK_IM_MODULE fixed the problem (thank you for that hint,  but it'd be nice if this were fixed;  took some careful wording of my search query to turn this up.)

**Comment by Sophira** [comment]
I can confirm this is still an issue in 2.4.2. I ran into this problem just now.

In my case, since I use ibus, using `GTK_IM_MODULE=ibus` worked.

**Comment by Sophira** [comment]
It should be noted that [wxWidgets calls XIM "unsupported and obsolete", and recommends against its use](https://wxwidgets.org/docs/faq/gtk/#xim):

> **Why entering accented letters or other non-ASCII characters doesn’t work?**
> 
> Please check that you don’t use unsupported and obsolete XIM input method manager by doing `echo $GTK_IM_MODULE` in a terminal window. If this outputs “xim”, please do `unset GTK_IM_MODULE` or install `ibus` package (exact name varies on the distribution used) and log out and in again, which should normally set `GTK_IM_MODULE=ibus`.
> 
> Using XIM results in multiple problems with both input and appearance (e.g. it can result in noticeable flickering even when not using any non-ASCII characters at all), so please avoid using it.

As such, this is probably not the only problem you'd encounter by using XIM. If you can, you're probably best off migrating to another input method, such as IBus.

(That said, I do wish I knew why this occurs. It does feel strange.)
