### ISSUE TITLE
Removing a track doesn't close the UI of an effect on that track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5747]
### Steps to reproduce

1. Add track (A)
2. Add another track (B)
3. Add an effect to the track A and open its UI
4. Add an effect to the track B and open its UI
5. Delete track A

### Expected behavior

The effect from track A gets closed

### Actual behavior

The effect from track A remains open

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by crsib** [comment]
I think that this bug is at least P2 and a ship blocker for 3.5. @LWinterberg please comment.

This is a regression from some of the latest refactoring merged in,

**Comment by LWinterberg** [comment]
I'd agree with that assessment

**Comment by dozzzzer** [comment]
This bug isn't a regression, it's been existing ever since we introduced non-modality for realtime effects, i.e. 3.3.0

**Comment by crsib** [comment]
> This bug isn't a regression, it's been existing ever since we introduced non-modality for realtime effects, i.e. 3.3.0

Non modality was introduced in 3.2.0, and I have fixed similar issue for that release. I can't reproduce this issue in 3.2.5 or 3.3.3

**Comment by dozzzzer** [comment]
Right. Correction to my previous comment: further testing shows that the bug was introduced in 3.2.3

**Comment by nalin243** [comment]
The same thing happens when you:

- Add track A
- Add track B
- Add an effect to B and open it's ui
- Add an effect to A and open it's ui
- Close track B

The ui for track B in this case remains open. This  happens if you delete any track which is not in focus. I even tried it with three and four tracks and whenever I close a track which is not in focus the ui remains open.

**Comment by dozzzzer** [comment]
Still reproducible as of 3.6.2 Beta:

https://github.com/user-attachments/assets/06d5a7d7-91c4-445f-9b1a-2abaa72ad292

**Comment by dozzzzer** [comment]
This will be fixed in Audacity 4.
