### ISSUE TITLE
A crash when the Cloud upload is aborted via Cmd + Q

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6053]
### Steps to reproduce

1. Generate 10-min tone
2. Initiate the Cloud upload
3. While upload is in progress, press Cmd (Ctrl) + Q
4. Click "Stop" in the appeared dialog
5. Observe

### Expected behavior

No crash

### Actual behavior

Audacity closes, followed by the crash report dialog.

Sentry: https://sentry.audacityteam.org/share/issue/0e72537783cd446eaa4a64b2f83ce2b8/

### Audacity Version

other

### Operating system

macOS 14.3

**Comment by crsib** [comment]
I can't reproduce this crash

**Comment by crsib** [comment]
Probably I have fixed it. I have surely fixed one of the issues

**Comment by dozzzzer** [comment]
The issue is still reproducible

**Comment by chinakov** [comment]
<img width="547" alt="image" src="https://github.com/audacity/audacity/assets/139755141/61d23958-ee80-4299-bdab-fb5544596d5d">
If the User presses 'CMD+Q' during the project upload process, the above pictured window is now shown to the User in latest Beta-3.5.0 Branch (https://github.com/audacity/audacity/actions/runs/8417667578)

**Comment by dozzzzer** [comment]
> the above pictured window is now shown to the User

Correct.  But this dialog was shown originally, so that isn't what this issue is all about.
Upon clicking Stop in the said dialog, the crash is still happening for me.

**Comment by dozzzzer** [comment]
I can still reproduce it on macOS in this build: https://github.com/audacity/audacity/actions/runs/8433683091

**Comment by dozzzzer** [comment]
Tested

**Comment by dozzzzer** [comment]
Still reproducible on macOS in https://github.com/audacity/audacity/actions/runs/8703671628

**Comment by dozzzzer** [comment]
No longer reproducible
