### ISSUE TITLE
[AU4] Track - Resizing tracks

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6768]
Allowing Users to resize tracks

[Figma Link](https://www.figma.com/design/k5rS9tnZl60nYmhJhvI2vf/Track-headers?node-id=280-46695)

**Comment by dozzzzer** [comment]
@kryksyh 

1. When hovering over the track panel's edges, the cursor doesn't change to a proper type:
AU3: 
<img width="231" alt="image" src="https://github.com/user-attachments/assets/74072101-45de-4015-a09b-9260a9da9732">

2. When the track's height exceeds the window's height, no vertical scroll bar appears.

https://github.com/user-attachments/assets/6338893e-bdf8-4c0e-ae25-1b17ef03f300

3. When in the collapsed state, the track panel should have the Mute and Solo buttons over here:

<img width="401" alt="image" src="https://github.com/user-attachments/assets/8a76a465-c521-4b0f-8f67-cdac25add350">

4. When the track is collapsed, observe how the title bars of some clips stick and some don't as I hover over them. I assume the correct behavior here would be to show the title bar as long as the cursor hovers over the clip and to hide it as soon as it moves away, am I right @DilsonsPickles ? Or do we need to show title bar on each clip at all times?

https://github.com/user-attachments/assets/ece08881-32ea-4374-86d4-7fbadb4eb3c9

**Comment by kryksyh** [comment]
@dozzzzer @chinakov 

1 & 3 should be fixed in the latest build

2. Can't reproduce, does this always happen to you?

4. Is not related to this PR, I would rather not to mix changes for separate modules in a single PR. Could you create a separate tasks for it?

**Comment by chinakov** [comment]
1. When hovering

**Comment by chinakov** [comment]
Also, regarding the number 4 on the list - in the latest build of the attached PR the issue is not reproducible for me. It seems that it's behaving correctly. 

https://github.com/user-attachments/assets/66944944-740c-42c4-80f9-55fb8a9a6d9f

**Comment by kryksyh** [comment]
@chinakov this may be present only on macos, it does happen to me

**Comment by dozzzzer** [comment]
@kryksyh Item no. 1 is still reproducible in the latest MacOS build:

Here I demonstrate it (observe how the cursor is flickering and for a fraction of a second it does change to the double-headed arrow but then reverts to the pointer one):

https://github.com/user-attachments/assets/4c369814-faf8-46c8-9550-ed4b413b0f68

Also, if you enlarge the track, scroll down, then scroll back up, its track panel appears broken:


https://github.com/user-attachments/assets/5d5a6de9-87e2-489a-84d9-1b98a792586c

>  Could you create a separate tasks

Sure

**Comment by dozzzzer** [comment]
@kryksyh Another thing is that the volume/pan tooltips show up when hovering in a halfway minimized state:

<img width="434" alt="image" src="https://github.com/user-attachments/assets/7d0680d8-3eb0-435a-bff1-2c69a2ded13d">

**Comment by dozzzzer** [comment]
@kryksyh UPD: I cannot reproduce the issue with the wrong cursor type as described above anymore.
When on hover, the cursor always changes to the double-headed arrow.
However, there's another problem: if I hold down LMB and move the cursor up or down swiftly enough, the cursor gets reset to the regular pointer type.


https://github.com/user-attachments/assets/4883ecc6-2253-4f2d-9d41-6baaf64d03ea

**Comment by kryksyh** [comment]
@dozzzzer yeah, the last one is the issue that we have no good solution for, I believe. This is a limitation on how QML works. It is also present in MuseScore.

**Comment by kryksyh** [comment]
@dozzzzer all found issues should be fixed except the flickering mouse cursor.

**Comment by dozzzzer** [comment]
> the volume/pan tooltips show up when hovering in a halfway minimized state

this issue remains present in the latest PR

**Comment by dozzzzer** [comment]
@kryksyh 

- If you have two tracks and you enlarge the upper one, so that its height exceeds the screen height, and then try to resize either of the two tracks ever so slightly, you'll see that the height of the track you're trying to resize jumps unexpectedly. Hope this can be seen on this video:

https://github.com/user-attachments/assets/b7fad7bf-33d4-402c-8ec7-732b953351b8

**Comment by dozzzzer** [comment]
Tested
